import type { TemplateDefinition } from '@/types/template';

export const popTemplate = {
  name: 'pop',
  label: 'ポップ',
  cssVars: {
    '--accent': '#FF6B35',
    '--accent-light': '#FFE4D4',
    '--bg': '#FFFBF5',
    '--bg-secondary': '#FFF3E8',
    '--text': '#1A1A1A',
    '--font-heading': "'DM Sans', sans-serif",
    '--font-body': "'DM Sans', sans-serif",
    '--radius': '12px',
    '--texture': "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24'%3E%3Ccircle cx='12' cy='12' r='1.5' fill='%231A1A1A' opacity='0.07'/%3E%3C/svg%3E\")",
    '--card-shadow': '4px 4px 0 #000000',
    '--card-border': '3px solid #000000',
    '--button-shadow': '4px 4px 0 #000000',
    '--button-radius': '0px',
    '--heading-accent': '4px solid #000000',
    '--section-divider': 'none',
    '--hover-lift': '-6px',
  },
  defaultVariants: {
    hero: 'centered',
    features: 'grid',
    testimonials: 'cards',
    pricing: 'cards',
    pricing_table: 'simple',
    faq: 'two-column',
    cta: 'centered',
    steps: 'horizontal',
    stats: 'cards',
    logo_bar: 'static',
    gallery: 'grid',
    divider: 'gradient',
    form: 'simple',
    footer: 'minimal',
  },
} as const satisfies TemplateDefinition;
