import type { TemplateDefinition } from '@/types/template';

export const simpleTemplate = {
  name: 'simple',
  label: 'シンプル',
  cssVars: {
    '--accent': '#2B2B28',
    '--accent-light': '#EBEBEA',
    '--bg': '#FFFFFF',
    '--bg-secondary': '#F7F7F6',
    '--text': '#2B2B28',
    '--font-heading': "'Outfit', sans-serif",
    '--font-body': "'Outfit', sans-serif",
    '--radius': '4px',
    '--texture': 'none',
    '--card-shadow': 'none',
    '--card-border': '1px solid rgba(0,0,0,0.08)',
    '--button-shadow': 'none',
    '--button-radius': '6px',
    '--heading-accent': 'none',
    '--section-divider': 'none',
    '--hover-lift': '0px',
  },
  defaultVariants: {
    hero: 'centered',
    features: 'grid',
    testimonials: 'cards',
    pricing: 'cards',
    pricing_table: 'simple',
    faq: 'accordion',
    cta: 'centered',
    steps: 'horizontal',
    stats: 'row',
    logo_bar: 'static',
    gallery: 'grid',
    divider: 'gradient',
    form: 'simple',
    footer: 'minimal',
  },
} as const satisfies TemplateDefinition;
